[package]
name = "ellisp"
version = "0.1.0"
authors = ["Elias Nygren <elias.nygren@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2"
itertools = "0.7"
